from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class AgentPlugin(Protocol):
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def description(self) -> str: ...

    async def initialize(self) -> None: ...
    async def process(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def shutdown(self) -> None: ...

@runtime_checkable
class SignalScoringAgent(AgentPlugin, Protocol):
    async def score(self, trade_signal: dict[str, Any]) -> float:
        """Score a trade signal 0.0-1.0. Higher = more confident."""
        ...

    async def explain(self, trade_signal: dict[str, Any]) -> str:
        """Explain the scoring rationale."""
        ...
