apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: copytrader-ingress
  namespace: copytrader
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: app.copytrader.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8011
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8011
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard-ui
                port:
                  number: 80
