/**
 * Standard tooltip copy for metrics across the dashboard.
 * Use with MetricCard tooltip prop so users can understand terms (e.g. MOC Imbalance).
 */
export const METRIC_TOOLTIPS: Record<string, string> = {
  'Total P&L': 'Profit and loss across all positions and closed trades in the selected period.',
  'Win Rate': 'Percentage of trades that closed with a profit. Higher is better for consistency.',
  'Sharpe Ratio': 'Risk-adjusted return. Above 1 is good; above 2 is strong.',
  'Max Drawdown': 'Largest peak-to-trough decline in portfolio value. Lower (e.g. -5%) is better.',
  'MOC Imbalance': 'Market-on-Close order imbalance. Positive = more buy-than-sell MOC orders; can signal short-term direction into the close.',
  'GEX Net': 'Net gamma exposure from dealers. Negative GEX can mean dealers hedge in the direction of price moves (more volatility).',
  'Dealer Gamma Zone': 'Whether dealers are long or short gamma. Negative = dealers may amplify moves.',
  'Put/Call Ratio': 'Options put volume vs call volume. &lt;1 often bullish; &gt;1 can indicate hedging or bearish sentiment.',
  'ODTE Volume': 'Zero days to expiration options volume. High ODTE volume can increase gamma and volatility near expiry.',
  'VIX': 'CBOE Volatility Index. Measures expected 30-day S&P 500 volatility. Higher = more fear/uncertainty.',
  'Pipeline Health': 'Status of the signal pipeline (Research → Technical → Risk). Healthy = all agents running and responding.',
  'Total Signals Today': 'Number of trading signals generated by the pipeline today.',
  'Avg R:R': 'Average risk-to-reward ratio of signals. e.g. 2.3 means target is 2.3× the stop distance.',
  'Active Signals': 'Signals currently open (not yet closed or expired).',
  'SPX Price': 'Current S&P 500 index level.',
  'Open Errors': 'Frontend/backend errors not yet resolved.',
  'Fixed by Agent': 'Errors auto-resolved by the dev agent.',
  'Needs Admin': 'Errors that require human review.',
  'Fix Rate %': 'Percentage of logged errors that have been resolved.',
}

export function getMetricTooltip(title: string): string | undefined {
  return METRIC_TOOLTIPS[title]
}
