from enum import Enum


class ErrorCode(str, Enum):
    BROKER_TIMEOUT = "BROKER_TIMEOUT"
    BROKER_REJECTED = "BROKER_REJECTED"
    INSUFFICIENT_BUYING_POWER = "INSUFFICIENT_BUYING_POWER"
    RATE_LIMITED = "RATE_LIMITED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    POSITION_NOT_FOUND = "POSITION_NOT_FOUND"
    BLACKLISTED = "BLACKLISTED"
    KILL_SWITCH = "KILL_SWITCH"
    PARSE_ERROR = "PARSE_ERROR"
    SERIALIZATION_ERROR = "SERIALIZATION_ERROR"
    DUPLICATE_MESSAGE = "DUPLICATE_MESSAGE"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"
    UNKNOWN = "UNKNOWN"
